### ISSUE TITLE
normelise keys

### ISSUE THREAD

**Issue by zivoy** [Poly-Haven/Public-API#1]
can you normelise the keys in the DB?
for textures there are all these different keys
```
['nor_dx', 'arm', 'Displacement', 'rough_ao', 'blend', 'nor_gl', 'Rough', 'Diffuse', 'AO', 'gltf', 'ref', 
'spec', 'Bump', 'col1', 'col2', 'page', 'normal_gl', 'normal_dx', 'diff_png', 'col_03', 'col_02', 'col_01', 
'col_1', 'col_2', 'coll1', 'coll2', 'Metal', 'rough_diff', 'diff_polar', 'rough_polar', 'nor_polar', 'translucent']
```
all the `col1`, `col_1`, `col_01` and  `coll1` is not efficent and most of those only have 1 texture asociated.
and some like `page` is only used in 1 texture [book_pattern](https://polyhaven.com/a/book_pattern), so its probably better off as a col

**Comment by gregzaal** [comment]
There are certainly some assets that could have more standardized map names, but it's impossible to standardize this completely as some assets have multiple materials, variants, and unique maps specific to that case. 

The `page` map in book_pattern is not the texture color/diffuse/albedo, it's a separate pages image that's not even used in the material itself.

Maybe if you explain what you're trying to do I can help you figure out the intended way to go about it.

**Comment by zivoy** [comment]
I already finished the thing I was working on. I just found it inconvenient that I had to make this dictionary where most values point to the same things.

https://github.com/zivoy/LilySurfaceScrapper/blob/47e47f1d629e1a8ce1d6c0fffa705290f13c5565/blender/LilySurfaceScraper/Scrapers/PolyHavenTexturesScraper.py#L50-L79

So I was thinking of having it so that the names will be more consistent and make it easier to program dynamically around.
Like church_bricks_02 does not have a `Diffuse` map, but it's the only one with the `diff_png` map, so I'm suggesting having standard naming and pattern for the maps.
something like this:
```
(file_type)[_variation][_copyNumber]
```

where `file_type` is a unique name from this list
```
normal
arm
displacement
blend
roughness
diffuse
ao
gltf
specular
bump
Metal
translucent
```
`variation` is the variation on the original texture like gl, dx, polar or another map. and `copyNumber` is a 2 digit padded number for if it is a second map for a texture

and here are some examples of conversions
`nor_dx ` -> `noraml_dx`
the dx becomes a variation same for the ambient occlusion one below
`rough_ao` -> `roughness_ao`
`ref` -> `specular`
only aerial_mud_1 has the `ref` map
`col1` -> `diffuse`
`col1` becomes `diffuse` if there is no diffuse map already, otherwise it will become `diffuse_02` and bump the rest down one
`col_2` -> `diffuse_02`
`page` -> `diffuse_03`
in this case `page` becouses `diffuse_03` because book_pattern already has colour 1 and 2
`normal_gl` -> `normal_gl_02`
broken_wall already has `nor_gl` and its different from `normal_gl`
`rough_diff` -> `roughness_diffuse`
`diff_polar` -> `diffuse_polar`
polar just becomes a variation on the map name

This should help simplify the naming scheme a bunch.
Also, the `page` image is useful if you want to make a rough book model. Just it shouldn't be named `page` since it's the only one using that name.

**Comment by gregzaal** [comment]
Just giving this some closure:

The intended way to use assets in the API for Blender is to download the whole blend file and its included files, and append the material from the blend file into your scene. Though I do agree consistency in map names would be nice, this is not something that gets in the way of the intended use so we don't plan to address it.
