### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by ddesmond** [Poly-Haven/Public-API#2]
Seems you guys need to check your certificate. If you use letsencrypt you need to get fresh ones.
`requests.exceptions.SSLError: HTTPSConnectionPool(host='dl.polyhaven.org', port=443): Max retries exceeded with url: /file/ph-assets/HDRIs/exr/1k/skukuza_golf_1k.exr (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] `

**Comment by gregzaal** [comment]
Works fine for me :) This cert is not managed by us, `dl.polyhaven.org` is a cname alias to Backblaze's B2 servers. If there is an actual cert issue I'm sure they'd resolve it quickly, as we're not the only client on their domain.

**Comment by ddesmond** [comment]
Im not sure then why would requests throw such an error (need to force verify=False to make it work):
`SSLError(MaxRetryError("HTTPSConnectionPool(host='dl.polyhaven.org', port=443): Max retries exceeded with url: /file/ph-assets/HDRIs/exr/1k/anniversary_lounge_1k.exr (Caused by SSLError(SSLError(1, u'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)`

**Comment by gregzaal** [comment]
I believe I know how to resolve the issue. Could you send me a full traceback, the whole error message (what you shared above is just a part of it). To do this, you can delete any asset folders in your library that it might have made, and then start Blender from a command prompt [like this](https://transfer.sh/XQ1951/2022-08-22_16-52-19_explorer.mp4). Click the "Fetch assets" button, and then copy paste the entire console output here please :)

I need to know which lines are throwing that error precisely.

**Comment by ddesmond** [comment]
Closing as solved? 
merry xmass folks!
