### ISSUE TITLE
Request: Smaller preview filesizes (tonemapped ones)

### ISSUE THREAD

**Issue by ddesmond** [Poly-Haven/Public-API#3]
As a developer I want to be able to grab preview files which are not so large in filesize, it will also benefit you becouse your bandwith will be reduced. The tonemapped image could be requested in different size (full, or preview) so server could process either on the fly or from a cache. imagemagik or such first comes to mind. Downloading 200kb instead of 5mb could be a huge win for you! :)

Thanks for considering this!

**Comment by gregzaal** [comment]
We use BunnyCDN atm for image optimization, just check the thumbnail source on the site to see some examples:

`https://cdn.polyhaven.com/asset_img/thumbs/red_bricks_04.png?width=285&height=285`

Docs for manipulations you can do are here: https://support.bunny.net/hc/en-us/articles/360027448392-Bunny-Optimizer-Engine-Documentation

**Comment by ddesmond** [comment]
Thanks Greg, ive implemented that already!
