### ISSUE TITLE
API Documentation link broken

### ISSUE THREAD

**Issue by bpedazur** [Poly-Haven/Public-API#5]
https://redocly.github.io/redoc/?url=https://api.polyhaven.com/api-docs/swagger.json
![image](https://user-images.githubusercontent.com/30467510/180825688-76486d05-be5f-4d88-88a4-468e7b5aab1f.png)

**Comment by gregzaal** [comment]
Looks like: https://github.com/Redocly/redoc/issues/2009

Still works in firefox but not chromium. For now add `&nocors` to the end of the url (https://redocly.github.io/redoc/?url=https://api.polyhaven.com/api-docs/swagger.json&nocors).
